// Definizioni campi: etichetta e tipo di input
export const fieldDefinitions = {
  // Dati controparte
  NOME_CONTROPARTE: { label: "Nome e Cognome / Ragione Sociale", type: "text" },
  CF_CONTROPARTE: { label: "Codice Fiscale", type: "text" },
  LUOGO_NASCITA: { label: "Luogo di Nascita", type: "text" },
  DATA_NASCITA: { label: "Data di Nascita", type: "date" },
  INDIRIZZO_CONTROPARTE: { label: "Residenza / Indirizzo", type: "text" },
  SEDE_CONTROPARTE: { label: "Sede Legale Controparte", type: "text" },
  PIVA_CONTROPARTE: { label: "P.IVA Controparte", type: "text" },
  // Date e durata
  DATA_INIZIO: { label: "Data di Inizio", type: "date" },
  DATA_FINE: { label: "Data di Fine", type: "date" },
  DATA_CONTRATTO: { label: "Data del Contratto", type: "date" },
  LUOGO_STIPULA: { label: "Luogo di Stipula", type: "text" },
  DURATA_APPRENDISTATO: { label: "Durata Apprendistato (mesi)", type: "number" },
  DURATA_NDA: { label: "Durata Riservatezza (anni)", type: "number" },
  DURATA_FORNITURA: { label: "Durata Fornitura (continuativa)", type: "text" },
  // Lavoro
  MANSIONE: { label: "Mansione / Qualifica", type: "text" },
  LIVELLO: { label: "Livello e Categoria di Inquadramento", type: "text" },
  CCNL_APPLICABILE: { label: "CCNL Applicato", type: "text" },
  ORE_SETTIMANALI: { label: "Ore Settimanali", type: "number" },
  DISTRIBUZIONE_ORARIO: { label: "Distribuzione Orario (giorni e orari)", type: "textarea" },
  RETRIBUZIONE: { label: "Retribuzione Lorda (€)", type: "number" },
  GIORNI_PROVA: { label: "Periodo di Prova (giorni)", type: "number" },
  LUOGO_LAVORO: { label: "Luogo di Lavoro", type: "text" },
  TIPO_TEMPO: { label: "Tipo Rapporto (determinato/indeterminato)", type: "text" },
  TIPO_PART_TIME: { label: "Tipo Part-Time (verticale/orizzontale/misto)", type: "text" },
  TIPOLOGIA_APPRENDISTATO: { label: "Tipologia di Apprendistato", type: "text" },
  CAUSALE_TERMINE: { label: "Causale del Termine", type: "textarea" },
  TUTOR_AZIENDALE: { label: "Tutor Aziendale", type: "text" },
  PIANO_FORMATIVO: { label: "Piano Formativo (contenuti e ore)", type: "textarea" },
  ENTE_FORMATIVO: { label: "Ente Formativo Esterno", type: "text" },
  // Prestazioni e compensi
  OGGETTO_PRESTAZIONE: { label: "Oggetto della Prestazione", type: "textarea" },
  OGGETTO_COLLABORAZIONE: { label: "Oggetto della Collaborazione", type: "textarea" },
  OGGETTO_INCARICO: { label: "Oggetto dell'Incarico", type: "textarea" },
  OGGETTO_ACCORDO: { label: "Oggetto dell'Accordo", type: "textarea" },
  COMPENSO: { label: "Compenso (€)", type: "number" },
  MODALITA_PAGAMENTO: { label: "Modalità di Pagamento", type: "text" },
  IBAN_PAGAMENTO: { label: "IBAN per Pagamento", type: "text" },
  RIMBORSI_SPESE: { label: "Rimborsi Spese", type: "textarea" },
  // Appalti e forniture
  OGGETTO_LAVORI: { label: "Oggetto dei Lavori / Servizi", type: "textarea" },
  IMPORTO: { label: "Importo (€)", type: "number" },
  PENALI: { label: "Penali per Ritardo", type: "text" },
  LUOGO_ESECUZIONE: { label: "Luogo di Esecuzione", type: "text" },
  RIFERIMENTO_APPALTO_PRINCIPALE: { label: "Riferimento Contratto di Appalto Principale", type: "text" },
  GARANZIE_FIDEIUSSIONI: { label: "Garanzie e Fideiussioni", type: "textarea" },
  SUBAPPALTO_AMMESSO: { label: "Subappalto (ammesso/vietato)", type: "text" },
  MODALITA_COLLAUDO: { label: "Modalità di Collaudo", type: "textarea" },
  ASSICURAZIONI: { label: "Assicurazioni", type: "textarea" },
  SICUREZZA_POS: { label: "Sicurezza (POS/DUVRI)", type: "textarea" },
  VARIANTI: { label: "Varianti", type: "textarea" },
  OGGETTO_FORNITURA: { label: "Oggetto della Fornitura (beni/materiali)", type: "textarea" },
  QUANTITA: { label: "Quantità", type: "text" },
  PREZZO_UNITARIO: { label: "Prezzo Unitario (€)", type: "number" },
  DATA_CONSEGNA: { label: "Data di Consegna", type: "date" },
  LUOGO_CONSEGNA: { label: "Luogo di Consegna", type: "text" },
  MODALITA_RESO: { label: "Modalità di Reso", type: "textarea" },
  TRASPORTO_SPESE: { label: "Trasporto e Spese", type: "textarea" },
  // Noleggio / comodato
  TIPO_CONTRATTO: { label: "Tipo (Noleggio/Comodato)", type: "text" },
  DESCRIZIONE_BENE: { label: "Descrizione del Bene", type: "textarea" },
  LUOGO_BENE: { label: "Luogo di Consegna e Restituzione", type: "text" },
  TIPO_CANONE: { label: "Tipo Canone", type: "text" },
  IMPORTO_CANONE: { label: "Importo Canone (€)", type: "number" },
  CAUZIONE: { label: "Cauzione", type: "text" },
  STATO_BENE_CONSEGNA: { label: "Stato del Bene alla Consegna", type: "textarea" },
  MANUTENZIONE_OBBLIGHI: { label: "Obblighi di Manutenzione", type: "textarea" },
  RESPONSABILITA_DANNI: { label: "Responsabilità per Danni", type: "textarea" },
  GARANZIA: { label: "Garanzia", type: "text" },
  // NDA
  OGGETTO_NDA: { label: "Oggetto delle Informazioni Riservate", type: "textarea" },
  SCOPO_NDA: { label: "Scopo della Condivisione", type: "textarea" },
  PENALE_NDA: { label: "Penale (€)", type: "number" },
  OBBLIGHI_CESSAZIONE: { label: "Obblighi alla Cessazione", type: "textarea" },
  ECCEZIONI_RISERVATEZZA: { label: "Eccezioni alla Riservatezza", type: "textarea" },
  // Verbale
  CONDIZIONI: { label: "Contenuto / Punti Concordati", type: "textarea" },
  IMPEGNI_SPECIFICI: { label: "Impegni Specifici delle Parti", type: "textarea" },
  TEMPISTICHE: { label: "Tempistiche", type: "textarea" },
  // Clausole facoltative lavoro
  BENEFIT: { label: "Benefit (buoni pasto, auto, telefono)", type: "textarea" },
  STRAORDINARI: { label: "Straordinari", type: "textarea" },
  TRASFERTE_RIMBORSI: { label: "Trasferte e Rimborsi", type: "textarea" },
  PATTO_RISERVATEZZA: { label: "Patto di Riservatezza", type: "textarea" },
  PATTO_NON_CONCORRENZA: { label: "Patto di Non Concorrenza", type: "textarea" },
  SMART_WORKING: { label: "Smart Working", type: "textarea" },
  CLAUSOLE_ELASTICHE: { label: "Clausole Elastiche/Flessibili", type: "textarea" },
  STRUMENTI_FORNITI: { label: "Strumenti Forniti", type: "textarea" },
  PROPRIETA_INTELLETTUALE: { label: "Proprietà Intellettuale", type: "textarea" },
  MODALITA_ESECUZIONE: { label: "Modalità di Esecuzione", type: "textarea" },
  LUOGO_SVOLGIMENTO: { label: "Luogo di Svolgimento", type: "text" },
  // Generiche
  NOTE_AGGIUNTIVE: { label: "Note Aggiuntive", type: "textarea" },
  // Clausole facoltative aggiuntive (comuni)
  FORZA_MAGGIORE: { label: "Clausola di Forza Maggiore", type: "textarea" },
  SOSPENSIONE_CONTRATTO: { label: "Sospensione del Contratto", type: "textarea" },
  DIRITTO_RECESSO: { label: "Diritto di Recesso", type: "textarea" },
  COMUNICAZIONI_PARTI: { label: "Comunicazioni tra le Parti", type: "textarea" },
  SPESE_ACCESSORIE: { label: "Spese e Oneri Accessori", type: "textarea" },
  SOPRAVVENIENZE_NORMATIVE: { label: "Sopravvenienze Normative", type: "textarea" },
  // Clausole facoltative lavoro aggiuntive
  MALATTIA_INFORTUNIO: { label: "Malattia e Infortunio", type: "textarea" },
  ASSENZE_FERIE: { label: "Ferie, Permessi e Assenze", type: "textarea" },
  PROVE_QUALIFICA: { label: "Prove di Qualifica", type: "textarea" },
};